name: scrap_app
version: 1.7.0+7
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.2.3 <4.0.0'
dependencies:
  app_settings: ^5.1.1
  auto_size_text: ^3.0.0
  camera: ^0.11.0+2
  carousel_slider: ^5.0.0
  cloud_firestore: ^5.3.0
  country_picker: ^2.0.26
  cupertino_icons: ^1.0.2
  firebase_auth: ^5.2.0
  firebase_core: ^3.4.0
  firebase_messaging: ^15.1.0
  firebase_storage: ^12.2.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_local_notifications: ^17.2.2
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  flutter_widget_from_html: ^0.15.1
  get: 4.6.6
  get_storage: ^2.1.1
  google_fonts: ^6.1.0
  googleapis_auth: ^1.6.0
  http: ^1.2.2
  image_picker: ^1.0.7
  intl: ^0.19.0
  otpless_flutter: ^2.1.6
  path_provider: ^2.1.4
  permission_handler: ^11.3.1
  rive: ^0.13.12
  shared_preferences: ^2.2.3
  smooth_page_indicator: ^1.1.0
  url_launcher: ^6.3.0
  webview_flutter: ^4.0.0
  
dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter


flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/Fonts/
    - assets/RiveAssets/
    - assets/Backgrounds/
    - assets/
  fonts:
    - family: Intel
      fonts:
        - asset: assets\Fonts\Inter-Regular.ttf
        - asset: assets\Fonts\Inter-SemiBold.ttf
          weight: 600
    - family: poppins
      fonts:
        - asset: assets\Fonts\Poppins-Bold.ttf
          weight: 700